apiVersion: v1
kind: Service
metadata:
  labels:
    app: ip312s07-tables
    owner: ip312s07
  name: ip312s07-service 
  namespace: ip312
spec:
  ports:
  - name: http
    port: 7777
    protocol: TCP
    targetPort: 5000
  selector:
    app: ip312s07-tables
  type: ClusterIP