apiVersion: v1
kind: Service
metadata:
  labels:
    app: ip312s07-tables
    owner: ip312s07
  name: "{{.Release.Name}}-service" 
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: http
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.targetPort}}
  selector:
    app: ip312s07-tables
    owner: ip312s07
    environment: {{ .Release.Name }} 
  type: {{.Values.service.type}}